name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Check syntax
      run: |
        echo "Checking main files..."
        node -c src/index.js
        node -c setup.js
        echo "Syntax check passed!"

    - name: Validate JSON files
      run: |
        echo "Validating JSON files..."
        node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"
        node -e "JSON.parse(require('fs').readFileSync('config/default.json', 'utf8'))"
        for file in personalities/*.json; do
          echo "Checking $file"
          node -e "JSON.parse(require('fs').readFileSync('$file', 'utf8'))"
        done
        echo "All JSON files are valid!"

    - name: Check project structure
      run: |
        echo "Checking project structure..."
        test -d src
        test -d personalities
        test -d config
        test -f README.md
        test -f LICENSE
        echo "Project structure is valid!"
